#!/bin/bash

# ---------------------------------------------------------
# Yabai
# Mac mini — Everforest rice
# Initial configuration: SIP fully enabled
# ---------------------------------------------------------

# Layout
yabai -m config layout bsp
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# Window behaviour
yabai -m config window_placement second_child
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off

# Gaps
yabai -m config window_gap 16

yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config bottom_padding 16

# Leave room for SketchyBar
yabai -m config top_padding 56

# Mouse
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
