const fs=require('fs'),vm=require('vm'),assert=require('assert');
const base=process.argv[2];
const registry=JSON.parse(fs.readFileSync(base+'/packs/registry.json'));
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(base+'/IconResolver.js','utf8'),ctx);
const settings={pack:'magi-legacy',modulePacks:{},overrides:{global:{},modules:{}}};
for(const role of ['wifi','wifi-low','wifi-medium','wifi-high','bluetooth','bluetooth-connected','volume','volume-muted','brightness','battery','battery-charging','settings','night-light','dnd','power-profile','power-saver','airplane-mode','vpn','caffeine','lock','hibernate','shutdown','media-play','media-pause','media-next','media-previous','back','scan','connect','disconnect'])
 assert(ctx.resolve(registry,settings,role,'').icon.text);
const firstParty=registry.packs.find(pack=>pack.id==='magi-default');
assert(firstParty && firstParty.parent==='magi-legacy');
settings.pack='magi-default';
assert.equal(ctx.resolve(registry,settings,'wifi','').icon.kind,'svg');
assert.equal(ctx.resolve(registry,settings,'wifi','').icon.colorMode,'semantic');
assert.equal(ctx.resolve(registry,settings,'settings','').icon.kind,'glyph');
registry.packs.push({id:'test',font:'test',roles:{wifi:{kind:'glyph',text:'G'}},modules:{wifi:{wifi:{kind:'glyph',text:'M'}}},assets:{}});
settings.pack='test';assert.equal(ctx.resolve(registry,settings,'wifi','').icon.text,'G');
assert.equal(ctx.resolve(registry,settings,'wifi','wifi').icon.text,'M');
settings.modulePacks.wifi='magi-legacy';assert.notEqual(ctx.resolve(registry,settings,'wifi','wifi').icon.text,'M');
settings.overrides.global.wifi={source:'bundled',pack:'test',icon:'wifi'};
assert.equal(ctx.resolve(registry,settings,'wifi','wifi').icon.text,'M');
settings.overrides.modules.wifi={wifi:{source:'bundled',pack:'magi-legacy',icon:'bluetooth'}};
assert.equal(ctx.resolve(registry,settings,'wifi','wifi').icon.text,registry.packs[0].roles.bluetooth.text);
settings.overrides.modules.wifi.wifi={source:'user',assetId:'../../etc/passwd'};
assert(ctx.resolve(registry,settings,'wifi','wifi').diagnostic.includes('Invalid icon override'));
settings.overrides.modules.wifi.wifi={source:'user',assetId:'icon:'+'a'.repeat(64)+'.svg'};
assert.equal(ctx.resolve(registry,settings,'wifi','wifi').icon.kind,'user');
assert(ctx.resolve(registry,settings,'missing-role','').icon.text);
const testPack=registry.packs.find(pack=>pack.id==='test');
testPack.roles.scan={kind:'svg',assetId:'sample',colorMode:'fixed'};testPack.assets.sample='sample.svg';
assert.equal(ctx.resolve(registry,settings,'scan','').icon.path,'sample.svg');
assert.equal(ctx.resolve(registry,settings,'scan','').icon.colorMode,'fixed');
testPack.assets.sample='../../escape.svg';assert.equal(ctx.resolve(registry,settings,'scan','').icon.kind,'glyph');
registry.packs.push({id:'child',parent:'magi-legacy',baseUrl:'file:///tmp/pack/',roles:{wifi:{kind:'managed-svg',path:'wifi.svg'}},modules:{},assets:{}});
settings.pack='child';delete settings.modulePacks.wifi;delete settings.overrides.modules.wifi;delete settings.overrides.global.wifi;
assert.equal(ctx.resolve(registry,settings,'wifi','').icon.kind,'managed');
assert.equal(ctx.resolve(registry,settings,'wifi','').icon.colorMode,'semantic');
assert.equal(ctx.resolve(registry,settings,'bluetooth','').icon.text,registry.packs[0].roles.bluetooth.text);
console.log('Semantic roles, first-party SVG tint mode, precedence, parent fallback and path guards PASS');
