#!/bin/bash

# =========================================================
# JankyBorders
# Mac mini — Everforest Dark Hard
# =========================================================

options=(
    style=round
    width=5.0
    hidpi=on

    # Everforest foreground
    active_color=0xffd3c6aa

    # Everforest Dark Hard bg3
    inactive_color=0xff414b50
)

borders "${options[@]}"
